const AccountActionTypes = {
  GET_ACCOUNTS_START: "GET_ACCOUNTS_START",
  GET_ACCOUNTS_FAILURE: "GET_ACCOUNTS_FAILURE",
  GET_ACCOUNTS_SUCCESS: "GET_ACCOUNTS_SUCCESS",
  ADD_ACCOUNT_START: "ADD_ACCOUNT_START",
  ADD_ACCOUNT_FAILURE: "ADD_ACCOUNT_FAILURE",
  ADD_ACCOUNT_SUCCESS: "ADD_ACCOUNT_SUCCESS"
};

export default AccountActionTypes;
